//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentManagement.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENTATTRIBUTE
    {
        public decimal COMPONENTATTRIBUTEID { get; set; }
        public Nullable<decimal> ENVIRONMENTCOMPONENTID { get; set; }
        public string ATTRIBUTEKEY { get; set; }
        public string ATTRIBUTEVALUE { get; set; }
    
        public virtual ENVIRONMENTCOMPONENT ENVIRONMENTCOMPONENT { get; set; }
    }
}
