//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentManagement.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIRONMENTATTRIBUTE
    {
        public ENVIRONMENTATTRIBUTE()
        {
            this.ENVIRONMENTs = new HashSet<ENVIRONMENT>();
            this.ENVIRONMENTs1 = new HashSet<ENVIRONMENT>();
            this.ENVIRONMENTs2 = new HashSet<ENVIRONMENT>();
            this.ENVIRONMENTCOMPONENTS = new HashSet<ENVIRONMENTCOMPONENT>();
        }
    
        public decimal ATTRIBUTEID { get; set; }
        public string ATTRIBUTETYPE { get; set; }
        public string ATTRIBUTEVALUE { get; set; }
        public string ATTRIBUTEDESCRIPTION { get; set; }
    
        public virtual ICollection<ENVIRONMENT> ENVIRONMENTs { get; set; }
        public virtual ICollection<ENVIRONMENT> ENVIRONMENTs1 { get; set; }
        public virtual ICollection<ENVIRONMENT> ENVIRONMENTs2 { get; set; }
        public virtual ICollection<ENVIRONMENTCOMPONENT> ENVIRONMENTCOMPONENTS { get; set; }
    }
}
