//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvironmentManagement.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIRONMENTCOMPONENT
    {
        public ENVIRONMENTCOMPONENT()
        {
            this.COMPONENTATTRIBUTES = new HashSet<COMPONENTATTRIBUTE>();
            this.COMPONENTCONNECTIONS = new HashSet<COMPONENTCONNECTION>();
            this.COMPONENTCONNECTIONS1 = new HashSet<COMPONENTCONNECTION>();
        }
    
        public decimal ENVIRONMENTCOMPONENTID { get; set; }
        public Nullable<decimal> ENVIRONMENTID { get; set; }
        public string COMPONENTNAME { get; set; }
        public string ENVIRONMENTATTRIBUTE { get; set; }
    
        public virtual ICollection<COMPONENTATTRIBUTE> COMPONENTATTRIBUTES { get; set; }
        public virtual ICollection<COMPONENTCONNECTION> COMPONENTCONNECTIONS { get; set; }
        public virtual ICollection<COMPONENTCONNECTION> COMPONENTCONNECTIONS1 { get; set; }
        public virtual ENVIRONMENT ENVIRONMENT { get; set; }
    }
}
